version: 0.0
os: linux
files:
  - source: /transport/*.zip
    destination: /home/ubuntu/transport/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: startup.sh
      timeout: 300
      runas: root
