version: 0.0
os: linux
files:
  - source: /transport-module-1.0.jar
    destination: /
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: startup.sh
      timeout: 300
      runas: root
