version: 0.0
os: linux
files:
  - source: /tmp/output
    destination: /home/ubuntu/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: startup.sh
      timeout: 300
      runas: root
