version: 0.2

env:
  variables:
    MYSQL_HOST: "transport-db.c1nqtylunte8.us-east-1.rds.amazonaws.com"
    MYSQL_PORT: "3306"
    MYSQL_DATABASE: "transport"
    MYSQL_USERNAME: "admin"
    MYSQL_PASSWORD: "Admin@123456"

phases:
  pre_build:
    commands:
      - echo "Installing Java and Gradle"
      - apt-get update
      - apt-get install -y openjdk-11-jdk
      - java -version
      - wget https://services.gradle.org/distributions/gradle-7.2-bin.zip -P /tmp
      - unzip -d /opt/gradle /tmp/gradle-7.2-bin.zip
      - export PATH=$PATH:/opt/gradle/gradle-7.2/bin
      - gradle -version

  build:
    commands:
      - echo "Building Spring Boot application with Gradle"
      - gradle build

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "moving jarfile to output"
      - ls
      - mkdir -p /tmp/output/
      - mv build/libs/*.jar /tmp/output/

artifacts:
  files:
    - /tmp/output/*.jar
